services:
  - type: web
    name: fraud-detection-api
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: MAX_CONTENT_MB
        value: 2048
      - key: STATUS_CHECK_COOLDOWN
        value: 30
      - key: ADDITIONAL_CORS_ORIGINS
        value: "https://cryptic-minds-fraud-detection.vercel.app"
      - key: ADDITIONAL_CORS_ORIGINSS
        value: "https://crypticminds-frauddetection.onrender.com/"